### ISSUE TITLE
Model error after optimization with EnergyCostMin

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/MPCPy#152]
If trying to simulate a model after solving an optimization involving prices (e.g. EnergyCostMin), an error is raised where the input of the price cannot be found.  This is due to the dynamic addition of the price to the other_input dictionary by the optimization, which is not present in the original model.

**Comment by dhblum** [comment]
The error has been reproduced in the unittests with output:

======================================================================
ERROR: test_simulate_cost_opt (unittests.test_optimization.OptimizeSimpleFromJModelica)
Test the dynamic setting of a problem type.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dhbubu/git/mpcpy/MPCPy/unittests/test_optimization.py", line 193, in test_simulate_cost_opt
    model.simulate(self.start_time, self.final_time)
  File "/home/dhbubu/git/mpcpy/MPCPy/mpcpy/models.py", line 1163, in simulate
    self._simulate_fmu();
  File "/home/dhbubu/git/mpcpy/MPCPy/mpcpy/utility.py", line 328, in _simulate_fmu
    options = self._sim_opts);
  File "src/pyfmi/fmi.pyx", line 6744, in pyfmi.fmi.FMUModelME2.simulate (src/pyfmi/fmi.c:71963)
  File "src/pyfmi/fmi.pyx", line 311, in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src/pyfmi/fmi.c:6047)
  File "src/pyfmi/fmi.pyx", line 305, in pyfmi.fmi.ModelBase._exec_simulate_algorithm (src/pyfmi/fmi.c:5938)
  File "/home/dhbubu/JModelica/v2_0/JModelica/Python/pyfmi/fmi_algorithm_drivers.py", line 266, in __init__
    self.model.set(input_traj[0], input_traj[1].eval(self.start_time)[0,:])
  File "src/pyfmi/fmi.pyx", line 212, in pyfmi.fmi.ModelBase.set (src/pyfmi/fmi.c:4773)
  File "src/pyfmi/fmi.pyx", line 3785, in pyfmi.fmi.FMUModelBase2._set (src/pyfmi/fmi.c:41607)
  File "src/pyfmi/fmi.pyx", line 4545, in pyfmi.fmi.FMUModelBase2.get_variable_valueref (src/pyfmi/fmi.c:48631)
FMUException: The variable pi_e could not be found.
