### ISSUE TITLE
Simulate fmu with no inputs

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/MPCPy#58]
This issue is to fix an error that occurs if trying to simulate an fmu with no external inputs:

Traceback (most recent call last):
  File "/home/dhblum/git/mpcpy/MPCPy/unittests/test_models.py", line 69, in test_simulate_noinputs
    self.model.simulate(self.start_time, self.final_time);
  File "/home/dhblum/git/mpcpy/MPCPy/mpcpy/models.py", line 262, in simulate
    self._simulate_fmu();
  File "/home/dhblum/git/mpcpy/MPCPy/mpcpy/utility.py", line 254, in _simulate_fmu
    self._create_input_object_from_input_mpcpy_ts_list(self._input_mpcpy_ts_list);
  File "/home/dhblum/git/mpcpy/MPCPy/mpcpy/utility.py", line 343, in _create_input_object_from_input_mpcpy_ts_list
    self._input_object = self._dataframe_to_input_object(self._input_df[self.start_time_utc:self.final_time_utc]);
  File "/home/dhblum/git/mpcpy/MPCPy/mpcpy/utility.py", line 409, in _dataframe_to_input_object
    input_df_simtime = self._add_simtime_column(df);
  File "/home/dhblum/git/mpcpy/MPCPy/mpcpy/utility.py", line 139, in _add_simtime_column
    dt = t - t[0];
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 557, in __getitem__
    result = self.index.get_value(self, key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/index.py", line 1796, in get_value
    return tslib.get_value_box(s, key)
  File "pandas/tslib.pyx", line 753, in pandas.tslib.get_value_box (pandas/tslib.c:16375)
  File "pandas/tslib.pyx", line 769, in pandas.tslib.get_value_box (pandas/tslib.c:16126)
IndexError: index out of bounds

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/MPCPy/pull/59.
