### ISSUE TITLE
Collect measurements from CSV

### ISSUE THREAD

**Issue by dhblum** [lbl-srg/MPCPy#80]
This issue is to fix a bug in collecting measurements from a csv file where the resulting pandas series is named incorrectly and will not be identified as a measurement during parameter estimation.

**Comment by dhblum** [comment]
This is the Traceback:

Traceback (most recent call last):
  File "estimate_39.py", line 125, in <module>
    model.estimate(start_time, final_time, ['T039'])
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/models.py", line 228, in estimate
    self._estimate_method._estimate(self);
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/models.py", line 670, in _estimate
    self.opt_problem.optimize(Model.start_time, Model.final_time, measurement_variable_list = Model.measurement_variable_list);
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/optimization.py", line 111, in optimize
    self._problem_type._optimize(self, **kwargs);
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/optimization.py", line 374, in _optimize
    Optimization._package_type._parameterestimate(Optimization, kwargs['measurement_variable_list']);
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/optimization.py", line 434, in _parameterestimate
    self._solve();
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/optimization.py", line 610, in _solve
    self._create_external_data();
  File "/home/dhb-lx/git/mpcpy/MPCPy/mpcpy/optimization.py", line 639, in _create_external_data
    df_simtime[key].get_values()));
  File "/home/dhb-lx/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/home/dhb-lx/.local/lib/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/home/dhb-lx/.local/lib/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/home/dhb-lx/.local/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/home/dhb-lx/.local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5280)
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas/_libs/index.c:5126)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20523)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas/_libs/hashtable.c:20477)
KeyError: 'Tzone'

**Comment by dhblum** [comment]
Can fix by setting name of timeseries as measurement variable name during utility._dataframe_to_mpcpy_ts_variable().

**Comment by dhblum** [comment]
Closed by https://github.com/lbl-srg/MPCPy/pull/81.
