### ISSUE TITLE
MA27 3 tests failing and memory issue

### ISSUE THREAD

**Issue by krzysztofarendt** [lbl-srg/MPCPy#84]
I run all tests on issue47_add_modestpy, but it should apply also the master, because it was merged recently.

```
======================================================================
FAIL: test_get_statistics (unittests.test_optimization.OptimizeSimpleFromJModelica)
Test the getting of optimization result statistics.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krza/github/mpcpy/unittests/test_optimization.py", line 255, in test_get_statistics
    self.check_json(json_test, 'statistics.txt');
  File "/home/krza/github/mpcpy/unittests/testing.py", line 125, in check_json
    self.assertEqual(json_test, json_ref);
AssertionError: Lists differ: [u'Solve_Succeeded', 23, 12810... != [u'Solve_Succeeded', 23, 12810...

First differing element 2:
128103999.94378369
128103999.94378363

- [u'Solve_Succeeded', 23, 128103999.94378369]
?                                           ^

+ [u'Solve_Succeeded', 23, 128103999.94378363]
?                                           ^


======================================================================
FAIL: test_initial_constraint (unittests.test_optimization.OptimizeSimpleFromJModelica)
Test the optimization of a model with an initial constraint.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krza/github/mpcpy/unittests/test_optimization.py", line 329, in test_initial_constraint
    self.check_json(json_test, 'statistics_initial_constraint.txt');
  File "/home/krza/github/mpcpy/unittests/testing.py", line 125, in check_json
    self.assertEqual(json_test, json_ref);
AssertionError: Lists differ: [u'Solve_Succeeded', 22, 12818... != [u'Solve_Succeeded', 22, 12818...

First differing element 2:
128188999.94378418
128188999.9437842

- [u'Solve_Succeeded', 22, 128188999.94378418]
?                                          ^^

+ [u'Solve_Succeeded', 22, 128188999.9437842]
?                                          ^


======================================================================
FAIL: test_set_parameters (unittests.test_optimization.OptimizeSimpleFromJModelica)
Test the dynamic setting of parameters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krza/github/mpcpy/unittests/test_optimization.py", line 297, in test_set_parameters
    self.check_df_timeseries(df_test, 'optimize_set_parameters_2.csv');
  File "/home/krza/github/mpcpy/unittests/testing.py", line 61, in check_df_timeseries
    pd.util.testing.assert_frame_equal(df_test, df_ref);
  File "/home/krza/github/virtualenv/mpcpy/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1443, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "/home/krza/github/virtualenv/mpcpy/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1322, in assert_series_equal
    obj='{0}'.format(obj))
  File "pandas/_libs/testing.pyx", line 59, in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:4156)
  File "pandas/_libs/testing.pyx", line 173, in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:3274)
  File "/home/krza/github/virtualenv/mpcpy/local/lib/python2.7/site-packages/pandas/util/testing.py", line 1149, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 1] are different

DataFrame.iloc[:, 1] values are different (28.27586 %)
[left]:  [8.43266905918e-05, 3.7475879017e-05, 1.42683047757e-05, 0.000115965815394, 2.37280613559e-05, 1.80693284939e-05, 8.56922852871e-05, 2.56003688585e-05, 1.9566575902e-05, 9.30543831721e-05, 2.78366267774e-05, 2.13692676669e-05, 0.000101974279339, 3.05538924765e-05, 2.35810894817e-05, 0.000113002914724, 3.3925449672e-05, 2.63586436068e-05, 0.000126985747689, 3.82191748165e-05, 2.99501438624e-05, 0.000145289913826, 4.38722838392e-05, 3.47738818291e-05, 0.000170279983284, 5.16502604573e-05, 4.15940128262e-05, 0.000206430525863, 6.30261342367e-05, 5.19711777278e-05, 0.000263355475276, 8.12436524079e-05, 6.96659454813e-05, 0.000366159058761, 0.000115121172642, 0.000106624712873, 0.00060767848538, 0.000200048633565, 0.000231847649062, 0.00185046503459, 0.000851099004142, 564.692603033, 378.610703981, 524.523719689, 544.340244207, 561.122818136, 569.074379464, 596.681773954, 618.97638924, 629.297501586, 664.222380563, 691.648452739, 704.161882299, 745.806748851, 777.895011859, 792.386571279, 840.038947663, 876.240364047, 892.462019637, 945.306637951, 985.001793064, 1002.6759087, 1059.80866035, 1102.3183607, 1121.14244828, 1181.58585351, 1226.18274797, 1245.83464303, 1308.5545759, 1354.47560086, 1374.61897492, 1438.54235747, 1485.00179308, 1505.29190834, 1569.32507124, 1615.5279853, 1635.61759315, 1698.66498872, 1743.82083819, 1763.36612077, 1824.34906806, 1867.68522545, 1886.35167846, 1944.22681982, 1985.00179309, 2002.46994923, 2056.24710242, 2093.7632221, 2109.73411728, 2158.49321779, 2192.10857427, 2206.30886295, 2249.21570652, 2278.35513338, 2290.54176557, 2326.8622817, 2351.02719687, 2360.99157682, 2390.10438889, 2408.8813256, ...]
[right]: [8.42782822087e-05, 3.74543627401e-05, 1.42601091764e-05, 0.000115899245415, 2.37144359513e-05, 1.80589511543e-05, 8.56430931368e-05, 2.55856687992e-05, 1.95553391838e-05, 9.30009653874e-05, 2.78206431705e-05, 2.13569962579e-05, 0.000101915741812, 3.05363492447e-05, 2.35675485599e-05, 0.000112938047136, 3.39059712833e-05, 2.63435084702e-05, 0.000126912854484, 3.81972319948e-05, 2.99329473506e-05, 0.000145206514805, 4.38470963767e-05, 3.47539167126e-05, 0.00017018224116, 5.16206088166e-05, 4.15701333108e-05, 0.000206312035312, 6.29899534843e-05, 5.19413423474e-05, 0.000263204313435, 8.11970159948e-05, 6.96259545551e-05, 0.000365948895289, 0.000115055093128, 0.000106563510575, 0.000607329708493, 0.000199933812413, 0.000231714573435, 0.00184940266218, 0.000850610362756, 564.692604652, 378.61069992, 524.523720871, 544.340243417, 561.122816784, 569.074381088, 596.68177298, 618.976388209, 629.29750321, 664.222379587, 691.648451711, 704.161883921, 745.806747875, 777.89501083, 792.386572902, 840.038946687, 876.240363016, 892.46202126, 945.306636976, 985.001792033, 1002.67591033, 1059.80865938, 1102.31835967, 1121.1424499, 1181.58585254, 1226.18274694, 1245.83464465, 1308.55457492, 1354.47559983, 1374.61897655, 1438.54235649, 1485.00179205, 1505.29190996, 1569.32507026, 1615.52798427, 1635.61759478, 1698.66498774, 1743.82083716, 1763.36612239, 1824.34906708, 1867.68522442, 1886.35168008, 1944.22681884, 1985.00179206, 2002.46995086, 2056.24710145, 2093.76322107, 2109.73411891, 2158.49321681, 2192.10857325, 2206.30886458, 2249.21570555, 2278.35513235, 2290.5417672, 2326.86228072, 2351.02719584, 2360.99157844, 2390.10438791, 2408.88132457, ...]

----------------------------------------------------------------------
Ran 165 tests in 12914.380s

FAILED (failures=3)
```

**Comment by dhblum** [comment]
Thanks for reporting this.

I get that all tests pass OK using the mumps solver in JModelica in 919s using my desktop computer on Ubuntu 16.04.

These fails are when using the MA27 solver with JModelica.  The fails are very small numerical differences that should be accepted with a resonable tolerance in the unit tests.  Such a tolerance needs to be implemented.

In addition, the MA27 solver requires more memory during the test test_models.EstimateFromJModelicaEmulationFMU.

I am opening seperate issues to address these developments.

**Comment by dhblum** [comment]
Correction, the MA27 memory issue arises in the test test_models.EstimateFromJModelicaRealCSV.

**Comment by dhblum** [comment]
Closed via https://github.com/lbl-srg/MPCPy/issues/85 and https://github.com/lbl-srg/MPCPy/issues/86.
